package beans;
// Generated 19.07.2017 21:43:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUsers generated by hbm2java
 */
@Entity
@Table(name="t_users"
    ,schema="public"
)
public class TUsers  implements java.io.Serializable {


     private long id;
     private String FName;
     private String FPassword;
     private String FPhone;
     private String FAddress;
     private String FEmail;

    public TUsers() {
    }

	
    public TUsers(long id) {
        this.id = id;
    }
    public TUsers(long id, String FName, String FPassword, String FPhone, String FAddress, String FEmail) {
       this.id = id;
       this.FName = FName;
       this.FPassword = FPassword;
       this.FPhone = FPhone;
       this.FAddress = FAddress;
       this.FEmail = FEmail;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="f_name")
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }

    
    @Column(name="f_password")
    public String getFPassword() {
        return this.FPassword;
    }
    
    public void setFPassword(String FPassword) {
        this.FPassword = FPassword;
    }

    
    @Column(name="f_phone")
    public String getFPhone() {
        return this.FPhone;
    }
    
    public void setFPhone(String FPhone) {
        this.FPhone = FPhone;
    }

    
    @Column(name="f_address")
    public String getFAddress() {
        return this.FAddress;
    }
    
    public void setFAddress(String FAddress) {
        this.FAddress = FAddress;
    }

    
    @Column(name="f_email")
    public String getFEmail() {
        return this.FEmail;
    }
    
    public void setFEmail(String FEmail) {
        this.FEmail = FEmail;
    }




}


